### ISSUE TITLE
Update 8

### ISSUE THREAD

**Issue by LVXFERRE** [mircearoata/SatisfactoryAdvancedLogistics#29]
Hello, Please can you update the mod for the experimental branch update 8?

**Comment by mircearoata** [comment]
Yes, I will update the mod, most likely in the coming week

**Comment by Chilu23** [comment]
Hey, any news on updating this mod?

**Comment by LVXFERRE** [comment]
> Yes, I will update the mod, most likely in the coming week

News?

**Comment by mircearoata** [comment]
Hi! I've been very busy with university work, so I haven't had much time for modding lately. I did, however, try to update the mod a couple of days ago, and while it did "just work" (it loaded and buildings worked fine), the UI text boxes were white text on a white background for some reason, and when trying to fix that, the editor crashed every time when opening that widget...

With the UE 5.2 update coming soon, though, I think I will wait for that, instead of fixing it now and having the mod break again just weeks after updating it.

**Comment by LVXFERRE** [comment]
Hey, I hope the update for the mod will be out soon. Thx for your work mate!!

**Comment by LVXFERRE** [comment]
News?

**Comment by mircearoata** [comment]
Finally had time today to do it. I had to go pretty deep in the Unreal Engine source to find out why the editor was crashing on that widget. As it turns out, it was because of a really weird localization issue...
